### PR TITLE
Fix issue #9. Skip extract when a representer is passed as argument.

### PR DESCRIPTION
**Pull request by Titinux**
@apotonick I've made a pull request with the correction you suggested.

### CODE REVIEW

**Comment by emaglio** [comment]
@Titinux thank you so much for this. Do you mind to add a quick test to cover this changes?

**Comment by oleg-kiviljov** [comment]
can this be merged now ? :)

**Comment by apotonick** [comment]
No, there is no test for that, which means I will forget it when I revisit it in a few days.

**Comment by apotonick** [comment]
But since I revisit it in a few days, I will merge it with a test! :grimacing:

**Comment by oleg-kiviljov** [comment]
any upd?

**Comment by fernandes** [comment]
@oleg-kiviljov no, no test added yet

**Pull request closed without merging**
