### PR TITLE
Use only symbols keys instead of strings

### PR DESCRIPTION
**Pull request by yogeshjain999**

### CODE REVIEW

**Comment by emaglio** [comment]
This looks good but I feel it will break a lot of people code and with the new TRB version we already request to change a lot of code since we have a class as Activity now so not sure if we should have this....not a blocking thing for this PR but we should think about this twice

**Comment by apotonick** [comment]
In trailblazer-context 0.1.3 we will have `Context::IndifferentAccess`
where `ctx["a"]` is equal to `ctx[:a]` for bw-compat. After that, all
internal keys must/should be symbols. :+1:

**Comment by yogeshjain999** [comment]
Awesome :+1:  Closing this then.

**Comment by apotonick** [comment]
This PR is important as it converts all string keys to symbols! :surfing_woman:

**Comment by yogeshjain999** [comment]
Ahh, right :sun_behind_large_cloud:

**Comment by emaglio** [comment]
@apotonick ok cool, then let's have this PR to add the dependency for `trailblazer-context >= 0.1.3`??

**Pull request merged**
